"""
@meta
name: test_deploy_agent_runtime
type: test
scope: unit
domain: docs
covers:
  - Deploy-time runtime rendering rewrites canonical repo-relative metadata paths to absolute machine paths
  - Deploy-time runtime rendering rewrites canonical local Python commands to absolute machine paths
  - Deploy checks compare against transformed runtime output rather than raw generated source
tags:
  - fast
  - ci-safe
lifecycle:
  status: active
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import yaml


REPO_ROOT = Path(__file__).resolve().parent.parent
DEPLOY_PATH = REPO_ROOT / "scripts" / "deploy_agent_runtime.py"
SCRIPTS_ROOT = str(REPO_ROOT / "scripts")

if SCRIPTS_ROOT not in sys.path:
    sys.path.insert(0, SCRIPTS_ROOT)


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load {path.name}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


DEPLOY = load_module("deploy_agent_runtime", DEPLOY_PATH)


def extract_frontmatter(rendered: str) -> dict[str, object]:
    if not rendered.startswith("---\n"):
        raise ValueError("Rendered text does not contain YAML frontmatter")
    closing_index = rendered.find("\n---", 4)
    if closing_index == -1:
        raise ValueError("Rendered text does not contain a closing YAML frontmatter delimiter")
    frontmatter = rendered[4:closing_index]
    return yaml.safe_load(frontmatter)


def test_rewrite_text_runtime_paths_keeps_relative_paths_by_default(tmp_path: Path) -> None:
    root = tmp_path / "repo"
    root.mkdir()

    source_text = """---
name: demo-skill
description: Demo
allowed-tools: []
hooks:
  pre:
    - python scripts/run_central_config_checks.py
  post: []
required_reads:
  - docs/operating_system/governance/repo-governance.md
required_outputs:
  - docs/superpowers/plans/demo-plan.md
tags: []
---

<!--
GENERATED FILE - DO NOT EDIT

Source: .agents/skills/demo-skill/SKILL.md
Generated by: scripts/sync_agent_adapters.py
To update: edit canonical source, then run sync.
-->

<MUST-READ>
- `docs/operating_system/prompt_templates/implementation-next-action-gate-prompt.md`
- `./scripts/get_gitnexus_freshness.ps1`
</MUST-READ>

<LINK>
- [Plan Guide](./docs/project-plan-guide.md)
- `./implementer-prompt.md`
</LINK>

See `docs/operating_system/prompt_templates/implementation-next-action-gate-prompt.md`
and `skills/demo/SKILL.md`.
"""

    target_root = tmp_path / "runtime"
    runtime_skill_dir = target_root / "skills" / "demo"
    rendered = DEPLOY._rewrite_text_runtime_paths(
        source_text,
        repo_root=root,
        target_root=target_root,
        current_runtime_dir=runtime_skill_dir,
    )
    frontmatter = extract_frontmatter(rendered)

    assert frontmatter["hooks"]["pre"] == ["python scripts/run_central_config_checks.py"]
    assert frontmatter["required_reads"] == ["docs/operating_system/governance/repo-governance.md"]
    assert frontmatter["required_outputs"] == ["docs/superpowers/plans/demo-plan.md"]
    assert "`docs/operating_system/prompt_templates/implementation-next-action-gate-prompt.md`" in rendered
    assert "`./scripts/get_gitnexus_freshness.ps1`" in rendered
    assert "[Plan Guide](./docs/project-plan-guide.md)" in rendered
    assert "`./implementer-prompt.md`" in rendered
    assert "Source: .agents/skills/demo-skill/SKILL.md" in rendered


def test_rewrite_text_runtime_paths_rewrites_frontmatter_and_source_lines_in_hardcode_mode(tmp_path: Path) -> None:
    root = tmp_path / "repo"
    root.mkdir()

    source_text = """---
name: demo-skill
description: Demo
allowed-tools: []
hooks:
  pre:
    - python scripts/run_central_config_checks.py
  post: []
required_reads:
  - docs/operating_system/governance/repo-governance.md
required_outputs:
  - docs/superpowers/plans/demo-plan.md
tags: []
---

<!--
GENERATED FILE - DO NOT EDIT

Source: .agents/skills/demo-skill/SKILL.md
Generated by: scripts/sync_agent_adapters.py
To update: edit canonical source, then run sync.
-->

<MUST-READ>
- `docs/operating_system/prompt_templates/implementation-next-action-gate-prompt.md`
- `./scripts/get_gitnexus_freshness.ps1`
</MUST-READ>

<LINK>
- [Plan Guide](./docs/project-plan-guide.md)
- `./implementer-prompt.md`
</LINK>

See `docs/operating_system/prompt_templates/implementation-next-action-gate-prompt.md`
and `skills/demo/SKILL.md`.
"""

    target_root = tmp_path / "runtime"
    runtime_skill_dir = target_root / "skills" / "demo"
    rendered = DEPLOY._rewrite_text_runtime_paths(
        source_text,
        repo_root=root,
        target_root=target_root,
        current_runtime_dir=runtime_skill_dir,
        rewrite_mode="hardcode",
    )
    frontmatter = extract_frontmatter(rendered)

    required_read_path = DEPLOY._runtime_absolute_string(target_root, "docs/operating_system/governance/repo-governance.md")
    required_output_path = DEPLOY._runtime_absolute_string(target_root, "docs/superpowers/plans/demo-plan.md")
    required_read_yaml = required_read_path.replace("\\", "\\\\")
    required_output_yaml = required_output_path.replace("\\", "\\\\")
    assert f'- "{required_read_yaml}"' in rendered
    assert f'- "{required_output_yaml}"' in rendered
    assert frontmatter["hooks"]["pre"] == ["python scripts/run_central_config_checks.py"]
    assert frontmatter["required_reads"] == [required_read_path]
    must_read_doc_path = DEPLOY._runtime_absolute_string(
        target_root,
        "docs/operating_system/prompt_templates/implementation-next-action-gate-prompt.md",
    )
    must_read_script_path = DEPLOY._repo_absolute_string(root, "scripts/get_gitnexus_freshness.ps1")
    link_doc_path = DEPLOY._runtime_absolute_string(target_root, "docs/project-plan-guide.md")
    link_skill_path = str((runtime_skill_dir / "implementer-prompt.md").resolve())
    assert f"`{must_read_doc_path}`" in rendered
    assert f"`{must_read_script_path}`" in rendered
    assert f"[Plan Guide]({link_doc_path})" in rendered
    assert f"`{link_skill_path}`" in rendered
    assert "`docs/operating_system/prompt_templates/implementation-next-action-gate-prompt.md`" in rendered
    assert "`skills/demo/SKILL.md`" in rendered
    source_path = DEPLOY._repo_absolute_string(root, ".agents/skills/demo-skill/SKILL.md")
    assert f"Source: {source_path}" in rendered


def test_plan_deploy_compares_against_transformed_runtime_output(tmp_path: Path) -> None:
    root = tmp_path / "repo"
    generated_root = root / "generated_agents" / "antigravity"
    target_root = tmp_path / "runtime"
    generated_root.mkdir(parents=True)
    target_root.mkdir(parents=True)

    generated_file = generated_root / "skills" / "demo" / "SKILL.md"
    generated_file.parent.mkdir(parents=True)
    generated_file.write_text(
        """---
name: demo
description: Demo
allowed-tools: []
hooks:
  pre:
    - python scripts/run_central_config_checks.py
  post: []
required_reads:
  - docs/operating_system/governance/repo-governance.md
required_outputs: []
tags: []
---
""",
        encoding="utf-8",
    )

    changes, issues, pairs = DEPLOY._plan_deploy(
        generated_root,
        target_root,
        repo_root=root,
        force=False,
        rewrite_mode="hardcode",
    )

    assert issues == []
    assert len(changes) == 1
    assert len(pairs) == 1
    _, destination, rendered = pairs[0]
    frontmatter = extract_frontmatter(rendered)
    required_read_path = DEPLOY._runtime_absolute_string(target_root, "docs/operating_system/governance/repo-governance.md")
    required_read_yaml = required_read_path.replace("\\", "\\\\")
    assert destination == target_root / "skills" / "demo" / "SKILL.md"
    assert f'- "{required_read_yaml}"' in rendered
    assert frontmatter["hooks"]["pre"] == ["python scripts/run_central_config_checks.py"]
    assert frontmatter["required_reads"] == [required_read_path]


def test_antigravity_target_deploys_into_nested_gemini_home() -> None:
    assert DEPLOY.PLATFORM_TARGETS["antigravity"] == Path.home() / ".gemini" / "antigravity"



def test_generated_runtime_files_skip_repo_skills_for_codex(tmp_path: Path) -> None:
    generated_root = tmp_path / "generated"
    generated_root.mkdir(parents=True)
    (generated_root / "AGENTS.md").write_text("root", encoding="utf-8")
    skill_file = generated_root / "skills" / "demo" / "SKILL.md"
    skill_file.parent.mkdir(parents=True, exist_ok=True)
    skill_file.write_text("skill", encoding="utf-8")

    codex_files = DEPLOY._iter_generated_runtime_files("codex", generated_root)
    claude_files = DEPLOY._iter_generated_runtime_files("claude", generated_root)

    assert generated_root / "AGENTS.md" in codex_files
    assert skill_file not in codex_files
    assert skill_file in claude_files


def test_runtime_stale_generated_files_marks_excluded_codex_skills(tmp_path: Path) -> None:
    generated_root = tmp_path / "generated"
    target_root = tmp_path / "runtime"
    generated_root.mkdir(parents=True)
    target_root.mkdir(parents=True, exist_ok=True)

    skill_file = generated_root / "skills" / "demo" / "SKILL.md"
    skill_file.parent.mkdir(parents=True, exist_ok=True)
    skill_file.write_text("generated skill", encoding="utf-8")

    runtime_skill = target_root / "skills" / "demo" / "SKILL.md"
    runtime_skill.parent.mkdir(parents=True, exist_ok=True)
    runtime_skill.write_text(
        "<!-- GENERATED FILE - DO NOT EDIT -->\nbody\n",
        encoding="utf-8",
    )

    stale = DEPLOY._runtime_stale_generated_files(
        generated_root,
        target_root,
        platform="codex",
    )

    assert runtime_skill in stale


def test_shared_skill_deploy_preserves_unrelated_installed_skills(tmp_path: Path) -> None:
    skills_root = tmp_path / "repo-skills"
    target_root = tmp_path / "user-skills"
    repo_skill = skills_root / "skill-demo"
    repo_skill.mkdir(parents=True)
    (repo_skill / "SKILL.md").write_text("demo skill\n", encoding="utf-8")
    unrelated_skill = target_root / "gitnexus-cli"
    unrelated_skill.mkdir(parents=True)
    (unrelated_skill / "SKILL.md").write_text("external skill\n", encoding="utf-8")

    changes, issues, pairs = DEPLOY._plan_shared_skill_deploy(
        skills_root,
        target_root,
        force=False,
    )

    assert issues == []
    assert len(changes) == 1
    assert changes[0].startswith("create: ")
    _, destination, rendered = pairs[0]
    assert destination == target_root / "skill-demo" / "SKILL.md"
    assert rendered == "demo skill"
    assert all("gitnexus-cli" not in change for change in changes)


def test_shared_skill_check_detects_missing_and_stale_repo_owned_files(tmp_path: Path) -> None:
    skills_root = tmp_path / "repo-skills"
    target_root = tmp_path / "user-skills"
    repo_skill = skills_root / "skill-demo"
    repo_skill.mkdir(parents=True)
    (repo_skill / "SKILL.md").write_text("demo skill\n", encoding="utf-8")
    deployed_skill = target_root / "skill-demo"
    deployed_skill.mkdir(parents=True)
    (deployed_skill / "extra.md").write_text("stale\n", encoding="utf-8")

    issues = DEPLOY._check_shared_skills(skills_root, target_root)

    assert f"Missing deployed shared skill file: {(deployed_skill / 'SKILL.md').as_posix()}" in issues
    assert f"Stale deployed shared skill file: {(deployed_skill / 'extra.md').as_posix()}" in issues
