"""
@meta
name: test_deploy_agent_runtime
type: test
scope: unit
domain: docs
covers:
  - Deploy-time runtime rendering rewrites canonical repo-relative metadata paths to absolute machine paths
  - Deploy-time runtime rendering rewrites canonical local Python commands to absolute machine paths
  - Deploy checks compare against transformed runtime output rather than raw generated source
tags:
  - fast
  - ci-safe
lifecycle:
  status: active
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import yaml


REPO_ROOT = Path(__file__).resolve().parent.parent
DEPLOY_PATH = REPO_ROOT / "scripts" / "deploy_agent_runtime.py"
SCRIPTS_ROOT = str(REPO_ROOT / "scripts")

if SCRIPTS_ROOT not in sys.path:
    sys.path.insert(0, SCRIPTS_ROOT)


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load {path.name}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


DEPLOY = load_module("deploy_agent_runtime", DEPLOY_PATH)


def extract_frontmatter(rendered: str) -> dict[str, object]:
    if not rendered.startswith("---\n"):
        raise ValueError("Rendered text does not contain YAML frontmatter")
    closing_index = rendered.find("\n---", 4)
    if closing_index == -1:
        raise ValueError("Rendered text does not contain a closing YAML frontmatter delimiter")
    frontmatter = rendered[4:closing_index]
    return yaml.safe_load(frontmatter)


def test_rewrite_text_runtime_paths_rewrites_frontmatter_and_source_lines(tmp_path: Path) -> None:
    root = tmp_path / "repo"
    root.mkdir()

    source_text = """---
name: demo-skill
description: Demo
allowed-tools: []
hooks:
  pre:
    - python scripts/run_central_config_checks.py
  post: []
required_reads:
  - docs/operating_system/governance/repo-governance.md
required_outputs:
  - docs/superpowers/plans/demo-plan.md
tags: []
---

<!--
GENERATED FILE - DO NOT EDIT

Source: .agents/skills/demo-skill/SKILL.md
Generated by: scripts/sync_agent_adapters.py
To update: edit canonical source, then run sync.
-->

# Demo
"""

    rendered = DEPLOY._rewrite_text_runtime_paths(source_text, root=root)
    frontmatter = extract_frontmatter(rendered)

    assert str(root / "docs" / "operating_system" / "governance" / "repo-governance.md") in rendered
    assert str(root / "docs" / "superpowers" / "plans" / "demo-plan.md") in rendered
    rewritten_command = DEPLOY._rewrite_command_to_absolute_repo_path(
        "python scripts/run_central_config_checks.py",
        root,
    )
    assert frontmatter["hooks"]["pre"] == [rewritten_command]
    assert frontmatter["required_reads"] == [
        DEPLOY._repo_absolute_string(root, "docs/operating_system/governance/repo-governance.md")
    ]
    source_path = DEPLOY._repo_absolute_string(root, ".agents/skills/demo-skill/SKILL.md")
    assert f"Source: {source_path}" in rendered


def test_plan_deploy_compares_against_transformed_runtime_output(tmp_path: Path) -> None:
    root = tmp_path / "repo"
    generated_root = root / "generated_agents" / "antigravity"
    target_root = tmp_path / "runtime"
    generated_root.mkdir(parents=True)
    target_root.mkdir(parents=True)

    generated_file = generated_root / "skills" / "demo" / "SKILL.md"
    generated_file.parent.mkdir(parents=True)
    generated_file.write_text(
        """---
name: demo
description: Demo
allowed-tools: []
hooks:
  pre:
    - python scripts/run_central_config_checks.py
  post: []
required_reads:
  - docs/operating_system/governance/repo-governance.md
required_outputs: []
tags: []
---
""",
        encoding="utf-8",
    )

    changes, issues, pairs = DEPLOY._plan_deploy(
        generated_root,
        target_root,
        root=root,
        force=False,
    )

    assert issues == []
    assert len(changes) == 1
    assert len(pairs) == 1
    _, destination, rendered = pairs[0]
    frontmatter = extract_frontmatter(rendered)
    assert destination == target_root / "skills" / "demo" / "SKILL.md"
    assert str(root / "docs" / "operating_system" / "governance" / "repo-governance.md") in rendered
    rewritten_command = DEPLOY._rewrite_command_to_absolute_repo_path(
        "python scripts/run_central_config_checks.py",
        root,
    )
    assert frontmatter["hooks"]["pre"] == [rewritten_command]
    assert frontmatter["required_reads"] == [
        DEPLOY._repo_absolute_string(root, "docs/operating_system/governance/repo-governance.md")
    ]
