"""
@meta
name: test_validate_generated_header_format
type: test
scope: unit
domain: docs
covers:
  - Generated Codex TOML provenance format
  - Generated DeepAgents project-agent provenance format
tags:
  - fast
  - ci-safe
lifecycle:
  status: active
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
VALIDATOR_PATH = REPO_ROOT / "scripts" / "validate_generated_header_format.py"


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load {path.name}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


VALIDATOR = load_module("validate_generated_header_format", VALIDATOR_PATH)


def test_validate_accepts_toml_and_deepagents_frontmatter_headers(tmp_path: Path) -> None:
    codex = tmp_path / "generated_agents" / "codex" / "agents" / "normal.toml"
    codex.parent.mkdir(parents=True)
    codex.write_text(
        "# GENERATED FILE - DO NOT EDIT\n#\n# Source: agents/normal.toml\n"
        "# Generated by: scripts/sync_agent_adapters.py\n"
        "# To update: edit canonical source, then run sync.\n\nname = \"normal\"\n",
        encoding="utf-8",
    )
    deepagents = tmp_path / ".deepagents" / "agents" / "normal" / "AGENTS.md"
    deepagents.parent.mkdir(parents=True)
    deepagents.write_text(
        "---\nname: normal\ndescription: >-\n  Role description\n---\n\n"
        "<!--\nGENERATED FILE - DO NOT EDIT\n\nSource: agents/normal.toml\n"
        "Generated by: scripts/sync_agent_adapters.py\n"
        "To update: edit canonical source, then run sync.\n-->\n\nReturn ROLE_OK.\n",
        encoding="utf-8",
    )

    assert VALIDATOR.validate(tmp_path) == []


def test_validate_rejects_html_header_before_generated_toml(tmp_path: Path) -> None:
    codex = tmp_path / "generated_agents" / "codex" / "agents" / "normal.toml"
    codex.parent.mkdir(parents=True)
    codex.write_text("<!--\nGENERATED FILE - DO NOT EDIT\n-->\n", encoding="utf-8")

    findings = VALIDATOR.validate(tmp_path)

    assert [(finding.path, finding.message) for finding in findings] == [
        ("generated_agents/codex/agents/normal.toml", "generated TOML file must start with canonical comment header.")
    ]


def test_validate_scans_deepagents_when_generated_agents_is_absent(tmp_path: Path) -> None:
    deepagents = tmp_path / ".deepagents" / "agents" / "normal" / "AGENTS.md"
    deepagents.parent.mkdir(parents=True)
    deepagents.write_text("broken\n", encoding="utf-8")

    findings = VALIDATOR.validate(tmp_path)

    assert [(finding.path, finding.message) for finding in findings] == [
        (".deepagents/agents/normal/AGENTS.md", "generated text file must start with frontmatter or generated HTML comment header.")
    ]
