"""Render and deploy the generated Switchyard auto-route runtime files."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import json
import math
import os
from pathlib import Path
import subprocess
import tempfile
import time
import tomllib
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen
from urllib.parse import urlparse


GENERATED_HEADER = (
    "# GENERATED FILE - DO NOT EDIT\n"
    "# Source: repo_config/switchyard-routing.toml\n"
    "# Generated by: scripts/manage_switchyard_runtime.py\n\n"
)
REQUIRED_LOG_FIELDS = (
    "route",
    "decision_source",
    "decision_score",
    "decision_threshold",
)
SUPPORTED_PICKERS = {"capable_first", "efficient_first"}
SUPPORTED_DECISION_SOURCES = {
    "dimensions",
    "override",
    "tests_passed",
    "llm-classifier",
    "fall_open",
}


@dataclass(frozen=True)
class RoutingPolicy:
    policy_version: int
    efficient_profile: str
    capable_profile: str
    route_id: str
    high_control_route_id: str
    picker: str
    confidence_threshold: float
    recent_turn_window: int


@dataclass(frozen=True)
class AgentProfile:
    name: str
    model_provider: str
    model: str
    rank: int
    source: Path


@dataclass(frozen=True)
class RoutingContract:
    policy: RoutingPolicy
    efficient: AgentProfile
    capable: AgentProfile
    provider_name: str
    upstream_base_url: str


def _load_toml(path: Path, label: str) -> dict[str, object]:
    try:
        payload = tomllib.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ValueError(f"{label} is missing: {path}") from exc
    except tomllib.TOMLDecodeError as exc:
        raise ValueError(f"Invalid {label} {path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise ValueError(f"Invalid {label} {path}: TOML root must be a table.")
    return payload


def _required_string(payload: dict[str, object], key: str, label: str) -> str:
    value = payload.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{label} `{key}` must be a non-empty string.")
    return value.strip()


def load_routing_policy(path: Path) -> RoutingPolicy:
    payload = _load_toml(path, "routing policy")
    allowed = {
        "policy_version",
        "efficient_profile",
        "capable_profile",
        "route_id",
        "high_control_route_id",
        "picker",
        "confidence_threshold",
        "recent_turn_window",
    }
    unexpected = sorted(set(payload) - allowed)
    if unexpected:
        raise ValueError(f"Routing policy has unsupported keys: {', '.join(unexpected)}.")

    policy_version = payload.get("policy_version")
    if policy_version != 1:
        raise ValueError("Routing policy `policy_version` must be 1.")
    efficient_profile = _required_string(payload, "efficient_profile", "Routing policy")
    capable_profile = _required_string(payload, "capable_profile", "Routing policy")
    route_id = _required_string(payload, "route_id", "Routing policy")
    high_control_route_id = _required_string(payload, "high_control_route_id", "Routing policy")
    if efficient_profile == capable_profile:
        raise ValueError("Routing policy efficient and capable profiles must differ.")
    if "low" in {efficient_profile, capable_profile}:
        raise ValueError("Routing policy cannot use `low` as an automatic endpoint.")
    if (efficient_profile, capable_profile) != ("normal", "high"):
        raise ValueError("Routing policy v1 automatic endpoints must be `normal` and `high`.")
    if route_id != "auto":
        raise ValueError("Routing policy v1 route_id must be `auto`.")
    if route_id == high_control_route_id:
        raise ValueError("Routing policy route IDs must differ.")

    picker = _required_string(payload, "picker", "Routing policy")
    if picker not in SUPPORTED_PICKERS:
        raise ValueError(f"Unsupported routing picker: {picker}")
    threshold = payload.get("confidence_threshold")
    if isinstance(threshold, bool) or not isinstance(threshold, (int, float)):
        raise ValueError("Routing policy `confidence_threshold` must be a number.")
    if not 0.0 <= float(threshold) <= 1.0:
        raise ValueError("Routing policy `confidence_threshold` must be between 0 and 1.")
    recent_window = payload.get("recent_turn_window")
    if isinstance(recent_window, bool) or not isinstance(recent_window, int) or recent_window < 1:
        raise ValueError("Routing policy `recent_turn_window` must be a positive integer.")
    return RoutingPolicy(
        policy_version=1,
        efficient_profile=efficient_profile,
        capable_profile=capable_profile,
        route_id=route_id,
        high_control_route_id=high_control_route_id,
        picker=picker,
        confidence_threshold=float(threshold),
        recent_turn_window=recent_window,
    )


def load_agent_profiles(agents_root: Path) -> dict[str, AgentProfile]:
    profiles: dict[str, AgentProfile] = {}
    for source in sorted(agents_root.glob("*.toml")):
        payload = _load_toml(source, "agent profile")
        values = {
            key: _required_string(payload, key, f"Agent profile {source}")
            for key in ("name", "model_provider", "model")
        }
        rank = payload.get("rank")
        if isinstance(rank, bool) or not isinstance(rank, int) or rank <= 0:
            raise ValueError(f"Agent profile `{source}` rank must be a positive integer.")
        if values["name"] != source.stem:
            raise ValueError(f"Agent profile name does not match filename: {source}")
        if values["name"] in profiles:
            raise ValueError(f"Duplicate agent profile: {values['name']}")
        profiles[values["name"]] = AgentProfile(
            name=values["name"],
            model_provider=values["model_provider"],
            model=values["model"],
            rank=rank,
            source=source,
        )
    if not profiles:
        raise ValueError(f"No agent profiles found under: {agents_root}")
    return profiles


def _safe_base_url(provider: dict[str, object]) -> str:
    base_url = _required_string(provider, "base_url", "Codex provider")
    parsed = urlparse(base_url)
    if parsed.username or parsed.password or parsed.query or parsed.fragment:
        raise ValueError("Codex provider base_url must not contain credentials or query data.")
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise ValueError("Codex provider base_url must be an HTTP(S) URL.")
    return base_url.rstrip("/")


def resolve_routing_contract(
    policy: RoutingPolicy,
    profiles: dict[str, AgentProfile],
    codex_config: dict[str, object],
) -> RoutingContract:
    efficient, capable = validate_static_contract(policy, profiles)

    provider_name = _required_string(codex_config, "model_provider", "Codex config")
    providers = codex_config.get("model_providers")
    if not isinstance(providers, dict) or not isinstance(providers.get(provider_name), dict):
        raise ValueError(f"Active Codex provider is unavailable: {provider_name}")
    if provider_name != efficient.model_provider:
        raise ValueError(
            f"Active Codex provider `{provider_name}` does not match profile provider "
            f"`{efficient.model_provider}`."
        )
    provider = providers[provider_name]
    if not isinstance(provider, dict):
        raise ValueError(f"Active Codex provider is invalid: {provider_name}")
    return RoutingContract(
        policy=policy,
        efficient=efficient,
        capable=capable,
        provider_name=provider_name,
        upstream_base_url=_safe_base_url(provider),
    )


def validate_static_contract(
    policy: RoutingPolicy,
    profiles: dict[str, AgentProfile],
) -> tuple[AgentProfile, AgentProfile]:
    try:
        efficient = profiles[policy.efficient_profile]
        capable = profiles[policy.capable_profile]
    except KeyError as exc:
        raise ValueError(f"Routing policy references missing profile: {exc.args[0]}") from exc
    if efficient.model_provider != capable.model_provider:
        raise ValueError("Automatic endpoint profiles must use the same model provider.")
    if efficient.model == capable.model:
        raise ValueError("Automatic endpoint profiles must use different model IDs.")
    if efficient.rank >= capable.rank:
        raise ValueError("Automatic endpoint ranks must increase from efficient to capable.")
    return efficient, capable


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_switchyard_routes(contract: RoutingContract) -> str:
    policy = contract.policy
    lines = [
        GENERATED_HEADER.rstrip("\n"),
        "schema_version = 1",
        "",
        "[llm_clients.upstream]",
        'format = "openai_responses"',
        f"base_url = {_toml_string(contract.upstream_base_url)}",
        'api_key_env = "SWITCHYARD_API_KEY"',
        "",
        "[targets.efficient]",
        f"id = {_toml_string(contract.efficient.model)}",
        'llm_client = "upstream"',
        "",
        "[targets.capable]",
        f"id = {_toml_string(contract.capable.model)}",
        'llm_client = "upstream"',
        "",
        "[routes.high_control]",
        f"id = {_toml_string(policy.high_control_route_id)}",
        'type = "passthrough"',
        'target = "capable"',
        "",
        "[routes.auto]",
        f"id = {_toml_string(policy.route_id)}",
        'type = "stage_router"',
        'capable_target = "capable"',
        'efficient_target = "efficient"',
        f"picker = {_toml_string(policy.picker)}",
        f"confidence_threshold = {policy.confidence_threshold:g}",
        f"recent_turn_window = {policy.recent_turn_window}",
        "",
    ]
    return "\n".join(lines)


def render_codex_auto() -> str:
    return GENERATED_HEADER + (
        'model_provider = "switchyard"\n'
        'model = "auto"\n\n'
        '[model_providers.switchyard]\n'
        'name = "Switchyard"\n'
        'base_url = "http://127.0.0.1:4000/v1"\n'
        'env_key = "SWITCHYARD_API_KEY"\n'
        'wire_api = "responses"\n'
    )


def _outputs(contract: RoutingContract, codex_home: Path, switchyard_home: Path) -> dict[Path, str]:
    return {
        switchyard_home / "routes.toml": render_switchyard_routes(contract),
        codex_home / "auto.config.toml": render_codex_auto(),
    }


def _semantic_toml(text: str, path: Path) -> dict[str, object]:
    try:
        payload = tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        raise ValueError(f"Existing runtime file is not valid TOML: {path}") from exc
    if not isinstance(payload, dict):
        raise ValueError(f"Existing runtime file must be a TOML table: {path}")
    return payload


def check_outputs(outputs: dict[Path, str]) -> list[str]:
    drift: list[str] = []
    for path, expected in outputs.items():
        if not path.is_file():
            drift.append(f"missing: {path}")
        elif path.read_text(encoding="utf-8") != expected:
            drift.append(f"drift: {path}")
    return drift


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle = tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
        delete=False,
    )
    temporary = Path(handle.name)
    try:
        with handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def deploy_outputs(outputs: dict[Path, str], *, replace_existing: bool = False) -> None:
    for path, expected in outputs.items():
        if not path.exists() or path.read_text(encoding="utf-8") == expected:
            continue
        if not replace_existing:
            raise RuntimeError(f"Refusing to overwrite existing runtime file: {path}")
    for path, expected in outputs.items():
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            _atomic_write(path, expected)


def _read_jsonl_since(path: Path, offset: int) -> list[dict[str, object]]:
    if not path.is_file():
        return []
    with path.open("rb") as handle:
        handle.seek(offset)
        rows: list[dict[str, object]] = []
        for raw_line in handle:
            if not raw_line.strip():
                continue
            try:
                row = json.loads(raw_line)
            except json.JSONDecodeError:
                continue
            if isinstance(row, dict):
                rows.append(row)
        return rows


def read_switchyard_row(path: Path, offset: int, *, timeout_seconds: float = 30.0) -> dict[str, object]:
    deadline = time.monotonic() + timeout_seconds
    while time.monotonic() < deadline:
        rows = _read_jsonl_since(path, offset)
        if rows:
            return rows[-1]
        time.sleep(0.1)
    raise TimeoutError(f"No complete Switchyard routing row appended: {path}")


def validate_smoke_row(row: dict[str, object]) -> None:
    if row.get("route") != "auto":
        raise ValueError("Smoke routing row must contain route=auto.")
    source = row.get("decision_source")
    if not isinstance(source, str) or source not in SUPPORTED_DECISION_SOURCES:
        raise ValueError("Smoke routing row has invalid decision_source.")
    if not isinstance(row.get("model"), str) or not row["model"]:
        raise ValueError("Smoke routing row must contain model.")
    if not isinstance(row.get("tier"), str):
        raise ValueError("Smoke routing row must contain tier.")
    for field in ("prompt_tokens", "completion_tokens", "total_tokens"):
        value = row.get(field)
        if isinstance(value, bool) or not isinstance(value, int) or value < 0:
            raise ValueError(f"Smoke routing row has invalid {field}.")
    score = row.get("decision_score")
    threshold = row.get("decision_threshold")
    if (score is None) != (threshold is None):
        raise ValueError("Smoke routing row score and threshold must appear together.")
    if score is not None:
        if isinstance(score, bool) or not isinstance(score, (int, float)) or not math.isfinite(score):
            raise ValueError("Smoke routing row has invalid decision_score.")
        if (
            isinstance(threshold, bool)
            or not isinstance(threshold, (int, float))
            or not math.isfinite(threshold)
            or not 0.0 <= threshold <= 1.0
        ):
            raise ValueError("Smoke routing row has invalid decision_threshold.")
    serialized = json.dumps(row, ensure_ascii=False).lower()
    for marker in ("api_key", "authorization", "cookie", "secret", "tool_result"):
        if marker in serialized:
            raise ValueError(f"Smoke routing row contains forbidden field marker: {marker}")


def _health_url(port: int) -> str:
    return f"http://127.0.0.1:{port}/health"


def run_smoke(
    routes_path: Path,
    routing_log_path: Path,
    summary_path: Path,
    *,
    run_id: str,
    server_executable: str = "switchyard-server",
    port: int = 4000,
    timeout_seconds: float = 30.0,
) -> dict[str, object]:
    routing_offset = routing_log_path.stat().st_size if routing_log_path.is_file() else 0
    process: subprocess.Popen[bytes] | None = None
    result: dict[str, object] = {
        "run_id": run_id,
        "status": "ERROR",
        "request_count": 0,
        "routing_row": None,
        "process_cleaned": False,
    }
    try:
        server_env = os.environ.copy()
        if not server_env.get("SWITCHYARD_API_KEY") and server_env.get("OPENAI_API_KEY"):
            server_env["SWITCHYARD_API_KEY"] = server_env["OPENAI_API_KEY"]
        process = subprocess.Popen(
            [
                server_executable,
                "--config",
                str(routes_path),
                "--host",
                "127.0.0.1",
                "--port",
                str(port),
                "--routing-log-file",
                str(routing_log_path),
            ],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            env=server_env,
        )
        deadline = time.monotonic() + timeout_seconds
        while time.monotonic() < deadline:
            if process.poll() is not None:
                raise RuntimeError("Switchyard exited before health check.")
            try:
                with urlopen(_health_url(port), timeout=0.5) as response:
                    if response.status == 200:
                        break
            except (OSError, URLError):
                time.sleep(0.1)
        else:
            raise TimeoutError("Switchyard health check timed out.")

        body = json.dumps(
            {
                "model": "auto",
                "input": "Return exactly SWITCHYARD_SMOKE_OK.",
                "max_output_tokens": 16,
                "store": False,
            }
        ).encode("utf-8")
        request = Request(
            f"http://127.0.0.1:{port}/v1/responses",
            data=body,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        api_key = os.environ.get("SWITCHYARD_API_KEY") or os.environ.get("OPENAI_API_KEY")
        if api_key:
            request.add_header("Authorization", f"Bearer {api_key}")
        result["request_count"] = 1
        try:
            with urlopen(request, timeout=timeout_seconds) as response:
                result["http_status"] = response.status
                response.read()
        except HTTPError as exc:
            result.update({"status": "BLOCKED", "http_status": exc.code, "reason": "provider_http_error"})
            return result
        except URLError as exc:
            result.update({"status": "BLOCKED", "reason": f"request_error:{type(exc.reason).__name__}"})
            return result

        row = read_switchyard_row(routing_log_path, routing_offset, timeout_seconds=timeout_seconds)
        validate_smoke_row(row)
        result.update({"status": "PASS", "routing_row": row})
        return result
    except (OSError, RuntimeError, TimeoutError, ValueError) as exc:
        result["reason"] = str(exc)
        return result
    finally:
        if process is not None:
            if process.poll() is None:
                process.terminate()
                try:
                    process.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait(timeout=5)
            result["process_cleaned"] = process.poll() is not None
        _atomic_write(summary_path, json.dumps(result, ensure_ascii=False, indent=2) + "\n")


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("validate", "render", "check", "deploy", "smoke"))
    parser.add_argument("--manifest", default="repo_config/switchyard-routing.toml")
    parser.add_argument("--codex-config", default="~/.codex/config.toml")
    parser.add_argument("--codex-home", default="~/.codex")
    parser.add_argument("--switchyard-home", default="~/.switchyard")
    parser.add_argument("--replace-existing", action="store_true")
    parser.add_argument("--run-id", default="switchyard-contract-ssot-v1")
    parser.add_argument("--routing-log")
    parser.add_argument("--summary-path")
    parser.add_argument("--server-executable", default="switchyard-server")
    parser.add_argument("--port", type=int, default=4000)
    parser.add_argument("--timeout-seconds", type=float, default=30.0)
    return parser


def _contract(args: argparse.Namespace) -> tuple[RoutingContract, dict[Path, str]]:
    manifest = Path(args.manifest).expanduser().resolve()
    codex_config_path = Path(args.codex_config).expanduser().resolve()
    codex_home = Path(args.codex_home).expanduser().resolve()
    switchyard_home = Path(args.switchyard_home).expanduser().resolve()
    policy = load_routing_policy(manifest)
    profiles = load_agent_profiles(manifest.parent.parent / "agents")
    contract = resolve_routing_contract(policy, profiles, _load_toml(codex_config_path, "Codex config"))
    return contract, _outputs(contract, codex_home, switchyard_home)


def _static_contract(args: argparse.Namespace) -> None:
    manifest = Path(args.manifest).expanduser().resolve()
    policy = load_routing_policy(manifest)
    profiles = load_agent_profiles(manifest.parent.parent / "agents")
    validate_static_contract(policy, profiles)


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        if args.command == "validate":
            _static_contract(args)
            print("Switchyard static policy validation passed.")
            return 0
        contract, outputs = _contract(args)
        if args.command == "render":
            for path, content in outputs.items():
                print(f"--- {path} ---")
                print(content, end="")
        elif args.command == "check":
            drift = check_outputs(outputs)
            if drift:
                for item in drift:
                    print(f"DRIFT: {item}")
                return 1
            print("Switchyard runtime drift check passed.")
        elif args.command == "deploy":
            deploy_outputs(outputs, replace_existing=args.replace_existing)
            print("Switchyard runtime deployed.")
        else:
            drift = check_outputs(outputs)
            if drift:
                raise RuntimeError("Smoke requires zero runtime drift: " + "; ".join(drift))
            switchyard_home = Path(args.switchyard_home).expanduser().resolve()
            routing_log = (
                Path(args.routing_log).expanduser().resolve()
                if args.routing_log
                else switchyard_home / "evidence" / "routing.jsonl"
            )
            summary_path = (
                Path(args.summary_path).expanduser().resolve()
                if args.summary_path
                else Path(tempfile.gettempdir()) / f"{args.run_id}-switchyard-smoke.json"
            )
            routes_path = switchyard_home / "routes.toml"
            result = run_smoke(
                routes_path,
                routing_log,
                summary_path,
                run_id=args.run_id,
                server_executable=args.server_executable,
                port=args.port,
                timeout_seconds=args.timeout_seconds,
            )
            print(json.dumps(result, ensure_ascii=False, indent=2))
            print(f"Smoke summary: {summary_path}")
            return 0 if result["status"] == "PASS" else 2
        return 0
    except (OSError, RuntimeError, ValueError) as exc:
        print(f"ERROR: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
