"""
@meta
name: render_harness_routing
type: script
domain: harness
distribution_tier: starter_kit
responsibility:
  - Render human harness routing guidance from canonical policy.
inputs:
  - repo_config/harness.yaml
outputs:
  - docs/operating_system/tooling/harness-routing.generated.md
tags:
  - harness
  - docs
  - generation
lifecycle:
  status: active
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml


DEFAULT_OUTPUT = "docs/operating_system/tooling/harness-routing.generated.md"


def render(root: Path) -> str:
    with (root / "repo_config" / "harness.yaml").open(encoding="utf-8") as handle:
        policy = yaml.safe_load(handle)
    lines = [
        "<!-- GENERATED FILE - DO NOT EDIT",
        "",
        "Source: repo_config/harness.yaml",
        "Generated by: scripts/render_harness_routing.py",
        "Regenerate: python scripts/render_harness_routing.py",
        "-->",
        "",
        "# Harness Routing",
        "",
        "Controller task packet selects one route. Rules stay mandatory. Agents return claimed results; harness returns verification evidence.",
        "",
        "| Task Type | Template | Role | Skills | Tools | Checks |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for name, route in policy["routes"].items():
        cells = [
            f"`{name}`",
            f"`{route['template']}`",
            f"`{route['role']}`",
            ", ".join(f"`{skill}`" for skill in route["skills"]),
            ", ".join(f"`{tool}`" for tool in route["tools"]),
            ", ".join(f"`{check}`" for check in route["checks"]),
        ]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


def sync(root: Path, output: Path, *, check: bool) -> int:
    expected = render(root)
    if check:
        if output.is_file() and output.read_text(encoding="utf-8") == expected:
            return 0
        print(f"Harness routing drift: {output}")
        return 1
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render harness routing guidance.")
    parser.add_argument("--repo-root", default=Path(__file__).resolve().parents[1])
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    root = Path(args.repo_root).resolve()
    output = Path(args.output)
    if not output.is_absolute():
        output = root / output
    return sync(root, output, check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
