"""
@meta
name: sync_agent_adapters
type: script
domain: governance
distribution_tier: starter_kit
responsibility:
  - Generate runtime adapter artifacts from canonical adapter mappings.
  - Enforce role-aware source inclusion/omission during adapter sync.
  - Detect and report drift in check mode for managed generated surfaces.
inputs:
  - Adapter mapping files under adapters/*
  - Canonical source files referenced by mapping rules
  - Repo adoption mode and role configuration
outputs:
  - Updated generated runtime artifacts across adapter destinations
  - Drift/failure diagnostics when --check is used
lifecycle:
  status: active
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from dataclasses import dataclass
import json
from pathlib import Path
import sys

import yaml

@dataclass(frozen=True)
class Mapping:
    source: str
    destination: str
    mode: str
    comment_prefix: str
    include_glob: str | None


GENERATED_BY = "scripts/sync_agent_adapters.py"
ROOT_INSTRUCTION_SOURCE = "docs/operating_system/templates/agents/root-AGENTS.template.md"
ROOT_INSTRUCTION_DESTINATION = "AGENTS.md"


def _render_json_from_yaml(text: str) -> str:
    payload = yaml.safe_load(text)
    return yaml.safe_dump(payload, sort_keys=False, allow_unicode=False)


def _strip_markdown_frontmatter(text: str) -> str:
    normalized = text.replace("\r\n", "\n")
    if not normalized.startswith("---\n"):
        return normalized
    parts = normalized.split("---\n", 2)
    if len(parts) < 3:
        return normalized
    return parts[2].lstrip("\n")


def _codex_rules_filename(path: Path) -> str:
    name = path.name
    if name.endswith("-rule.md"):
        return f"{name[:-len('-rule.md')]}.rules"
    if name.endswith(".md"):
        return f"{name[:-3]}.rules"
    return f"{name}.rules"


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Sync agent adapter outputs.")
    parser.add_argument("--check", action="store_true", help="Fail on drift without writing.")
    parser.add_argument(
        "--adapters-root",
        default="adapters",
        help="Adapters directory relative to repo root.",
    )
    parser.add_argument(
        "--platform",
        action="append",
        default=[],
        help="Platform to sync (repeatable). Overrides mode-driven defaults unless --all-platforms is set.",
    )
    parser.add_argument(
        "--all-platforms",
        action="store_true",
        help="Process all adapter mappings.",
    )
    return parser.parse_args()


def _load_mapping(path: Path) -> tuple[str, list[Mapping]]:
    payload = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"Invalid mapping yaml: {path}")
    platform = str(payload.get("platform", path.parent.name))
    mapping_items = payload.get("mappings")
    if not isinstance(mapping_items, list):
        raise ValueError(f"`mappings` must be a list in {path}")
    mappings: list[Mapping] = []
    for raw in mapping_items:
        if not isinstance(raw, dict):
            raise ValueError(f"Invalid mapping entry in {path}")
        mappings.append(
            Mapping(
                source=str(raw["source"]),
                destination=str(raw["destination"]),
                mode=str(raw.get("mode", "copy_file")),
                comment_prefix=str(raw.get("comment_prefix", "#")),
                include_glob=str(raw["include_glob"]) if "include_glob" in raw else None,
            )
        )
    return platform, mappings


def _render_generated_block(source_rel: str) -> str:
    return (
        "<!--\n"
        "GENERATED FILE - DO NOT EDIT\n\n"
        f"Source: {source_rel}\n"
        f"Generated by: {GENERATED_BY}\n"
        "To update: edit canonical source, then run sync.\n"
        "-->\n\n"
    )


def _strip_generated_block(raw: str) -> str:
    marker = "<!--\nGENERATED FILE - DO NOT EDIT\n"
    if not raw.startswith(marker):
        legacy_marker = "# GENERATED FILE - do not edit directly.\n"
        if raw.startswith(legacy_marker):
            rest = raw[len(legacy_marker) :]
            legacy_source = "# Source: `"
            if rest.startswith(legacy_source):
                line_end = rest.find("\n")
                if line_end != -1:
                    rest = rest[line_end + 1 :]
            return rest.lstrip("\n")
        return raw
    end = raw.find("-->\n")
    if end == -1:
        return raw
    return raw[end + len("-->\n") :].lstrip("\n")


def _render_with_header(text: str, *, source_rel: str, prefix: str) -> str:
    del prefix
    header = _render_generated_block(source_rel)
    normalized = _strip_generated_block(text.replace("\r\n", "\n"))
    if not normalized.startswith("---\n"):
        return header + normalized
    parts = normalized.split("---\n", 2)
    if len(parts) < 3:
        return header + normalized
    frontmatter = f"---\n{parts[1]}---\n"
    body = parts[2].lstrip("\n")
    return f"{frontmatter}\n{header}{body}"


def _inject_json_generated_metadata(payload: dict, *, source_rel: str) -> dict:
    clean_payload = dict(payload)
    clean_payload.pop("_generated", None)
    clean_payload.pop("_source", None)
    clean_payload.pop("_generated_by", None)
    clean_payload.pop("_do_not_edit", None)
    return {
        "_generated": True,
        "_source": source_rel,
        "_generated_by": GENERATED_BY,
        "_do_not_edit": "Edit canonical source and run sync.",
        **clean_payload,
    }


def _normalized(text: str) -> str:
    return text.replace("\r\n", "\n").rstrip("\n")


def _write_text_if_changed(path: Path, rendered: str) -> None:
    if path.exists():
        current = path.read_text(encoding="utf-8")
        if _normalized(current) == _normalized(rendered):
            return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(rendered, encoding="utf-8")

def _iter_matching_files(root: Path, pattern: str) -> list[Path]:
    return [path for path in root.glob(pattern) if path.is_file()]

def _remove_stale_files(dst_root: Path, expected: set[Path]) -> None:
    if not dst_root.exists():
        return
    generated = {path.relative_to(dst_root) for path in dst_root.rglob("*") if path.is_file()}
    for stale in generated - expected:
        (dst_root / stale).unlink(missing_ok=True)


def _expected_tree_paths(src_root: Path, pattern: str) -> set[Path]:
    return {path.relative_to(src_root) for path in _iter_matching_files(src_root, pattern)}


def _expected_codex_rules_paths(src_root: Path, pattern: str, dst_root: Path) -> set[Path]:
    return {
        (dst_root / _codex_rules_filename(path)).relative_to(dst_root)
        for path in _iter_matching_files(src_root, pattern)
    }


def _mapping_files_for_selection(adapters_root: Path, selected_platforms: set[str]) -> list[Path]:
    all_mappings = sorted(adapters_root.glob("*/mapping.yaml"))
    if not selected_platforms:
        return all_mappings
    return [path for path in all_mappings if path.parent.name in selected_platforms]


def _has_explicit_platform_selection(args: argparse.Namespace) -> bool:
    if args.all_platforms:
        return True
    cli_platforms = [
        item.strip()
        for item in (args.platform or [])
        if isinstance(item, str) and item.strip()
    ]
    return bool(cli_platforms)


def _resolve_platform_selection(root: Path, args: argparse.Namespace) -> tuple[set[str], str]:
    del root
    if args.all_platforms:
        return set(), "all-platforms"
    selected = {item.strip() for item in args.platform if item.strip()}
    if selected:
        return selected, "explicit"
    return {"codex"}, "default"



def _preserve_paths_for_destination(
    destination_preserve_paths: dict[Path, set[Path]],
    dst_root: Path,
) -> set[Path]:
    preserve: set[Path] = set(destination_preserve_paths.get(dst_root, set()))
    for other_root, other_paths in destination_preserve_paths.items():
        if other_root == dst_root:
            continue
        try:
            relative_root = other_root.relative_to(dst_root)
        except ValueError:
            continue
        preserve.update(relative_root / rel_path for rel_path in other_paths)
    return preserve


def _generated_agent_destination_roots(root: Path, mappings: list[Mapping]) -> set[Path]:
    generated_root = root / "generated_agents"
    owned_roots: set[Path] = set()
    for mapping in mappings:
        destination = root / mapping.destination
        try:
            destination.relative_to(generated_root)
        except ValueError:
            continue
        owned_roots.add(destination)
    return owned_roots


def _find_orphan_generated_surfaces(root: Path, mappings: list[Mapping]) -> list[Path]:
    generated_root = root / "generated_agents"
    if not generated_root.exists():
        return []
    owned_roots = _generated_agent_destination_roots(root, mappings)
    orphans: list[Path] = []
    for path in sorted(generated_root.rglob("*")):
        if not path.is_file():
            continue
        if any(path == owned or owned in path.parents for owned in owned_roots):
            continue
        orphans.append(path)
    return orphans


def _sync_file(root: Path, mapping: Mapping, *, check: bool) -> list[str]:
    src = root / mapping.source
    dst = root / mapping.destination
    if not src.exists():
        return [f"Missing source: {src.as_posix()}"]
    src_text = src.read_text(encoding="utf-8")
    source_rel = src.relative_to(root).as_posix()
    if mapping.mode == "render_json_from_yaml":
        payload = _inject_json_generated_metadata(yaml.safe_load(src_text) or {}, source_rel=source_rel)
        rendered = json.dumps(payload, indent=2) + "\n"
    elif mapping.mode == "render_root_doc":
        rendered = _render_with_header(src_text, source_rel=source_rel, prefix=mapping.comment_prefix)
    elif mapping.mode == "render_codex_rule_file":
        body = _strip_markdown_frontmatter(src_text)
        rendered = _render_with_header(
            body,
            source_rel=source_rel,
            prefix=mapping.comment_prefix,
        )
    else:
        rendered = _render_with_header(
            src_text,
            source_rel=source_rel,
            prefix=mapping.comment_prefix,
        )
    if check:
        if not dst.exists():
            return [f"Missing generated file: {dst.as_posix()}"]
        actual = dst.read_text(encoding="utf-8")
        if _normalized(actual) != _normalized(rendered):
            return [f"Drift detected: {dst.as_posix()}"]
        return []
    _write_text_if_changed(dst, rendered)
    return []


def _sync_tree(
    root: Path,
    mapping: Mapping,
    *,
    check: bool,
    preserve_paths: set[Path] | None = None,
) -> list[str]:
    src_root = root / mapping.source
    dst_root = root / mapping.destination
    if not src_root.exists():
        return [f"Missing source directory: {src_root.as_posix()}"]
    pattern = mapping.include_glob or "**/*"
    issues: list[str] = []
    expected_paths = _expected_tree_paths(src_root, pattern)
    for src in _iter_matching_files(src_root, pattern):
        rel = src.relative_to(src_root)
        dst = dst_root / rel
        rendered = _render_with_header(
            src.read_text(encoding="utf-8"),
            source_rel=src.relative_to(root).as_posix(),
            prefix=mapping.comment_prefix,
        )
        if check:
            if not dst.exists():
                issues.append(f"Missing generated file: {dst.as_posix()}")
                continue
            actual = dst.read_text(encoding="utf-8")
            if _normalized(actual) != _normalized(rendered):
                issues.append(f"Drift detected: {dst.as_posix()}")
            continue
        _write_text_if_changed(dst, rendered)
    if not check:
        _remove_stale_files(dst_root, preserve_paths or expected_paths)
    return issues


def _sync_codex_rules_tree(
    root: Path,
    mapping: Mapping,
    *,
    check: bool,
    preserve_paths: set[Path] | None = None,
) -> list[str]:
    src_root = root / mapping.source
    dst_root = root / mapping.destination
    if not src_root.exists():
        return [f"Missing source directory: {src_root.as_posix()}"]
    pattern = mapping.include_glob or "*.md"
    issues: list[str] = []
    expected_paths = _expected_codex_rules_paths(src_root, pattern, dst_root)
    for src in _iter_matching_files(src_root, pattern):
        dst = dst_root / _codex_rules_filename(src)
        body = _strip_markdown_frontmatter(src.read_text(encoding="utf-8"))
        rendered = _render_with_header(
            body,
            source_rel=src.relative_to(root).as_posix(),
            prefix=mapping.comment_prefix,
        )
        if check:
            if not dst.exists():
                issues.append(f"Missing generated file: {dst.as_posix()}")
                continue
            actual = dst.read_text(encoding="utf-8")
            if _normalized(actual) != _normalized(rendered):
                issues.append(f"Drift detected: {dst.as_posix()}")
            continue
        _write_text_if_changed(dst, rendered)
    if not check:
        _remove_stale_files(dst_root, preserve_paths or expected_paths)
    return issues



def _sync_root_instruction(root: Path, *, check: bool) -> list[str]:
    return _sync_file(
        root,
        Mapping(
            source=ROOT_INSTRUCTION_SOURCE,
            destination=ROOT_INSTRUCTION_DESTINATION,
            mode="render_root_doc",
            comment_prefix="#",
            include_glob=None,
        ),
        check=check,
    )


def run() -> int:
    args = parse_args()
    root = repo_root()
    adapters_root = root / args.adapters_root
    selected_platforms, selector = _resolve_platform_selection(root, args)
    mapping_files = _mapping_files_for_selection(adapters_root, selected_platforms)
    if not mapping_files:
        selected_display = ",".join(sorted(selected_platforms)) if selected_platforms else "all"
        print(
            f"No adapter mappings found for selection={selected_display} under {adapters_root.as_posix()} "
            f"(selector={selector})."
        )
        return 1
    selected_display = ",".join(sorted(selected_platforms)) if selected_platforms else "all"
    print(f"Adapter selection: {selected_display} (selector={selector})")
    issues: list[str] = _sync_root_instruction(root, check=args.check)
    destination_preserve_paths: dict[Path, set[Path]] = defaultdict(set)
    loaded_mappings: list[tuple[str, list[Mapping]]] = []
    all_mappings: list[Mapping] = []
    for mapping_file in mapping_files:
        platform, mappings = _load_mapping(mapping_file)
        loaded_mappings.append((platform, mappings))
        all_mappings.extend(mappings)
    for _, mappings in loaded_mappings:
        for mapping in mappings:
            dst_root = root / mapping.destination
            if mapping.mode == "copy_tree":
                src_root = root / mapping.source
                if src_root.exists():
                    pattern = mapping.include_glob or "**/*"
                    destination_preserve_paths[dst_root].update(
                        _expected_tree_paths(src_root, pattern)
                    )
            elif mapping.mode == "render_codex_rules_tree":
                src_root = root / mapping.source
                if src_root.exists():
                    pattern = mapping.include_glob or "*.md"
                    destination_preserve_paths[dst_root].update(
                        _expected_codex_rules_paths(src_root, pattern, dst_root)
                    )

    destination_roots = list(destination_preserve_paths.keys())
    for dst_root in destination_roots:
        for other_root in destination_roots:
            if other_root == dst_root:
                continue
            try:
                rel = other_root.relative_to(dst_root)
            except ValueError:
                continue
            destination_preserve_paths[dst_root].update(
                rel / path for path in destination_preserve_paths[other_root]
            )
    for platform, mappings in loaded_mappings:
        for mapping in mappings:
            dst_root = root / mapping.destination
            preserve_paths = _preserve_paths_for_destination(destination_preserve_paths, dst_root)
            if mapping.mode == "copy_tree":
                issues.extend(
                    _sync_tree(
                        root,
                        mapping,
                        check=args.check,
                        preserve_paths=preserve_paths,
                    )
                )
            elif mapping.mode == "render_codex_rules_tree":
                issues.extend(
                    _sync_codex_rules_tree(
                        root,
                        mapping,
                        check=args.check,
                        preserve_paths=preserve_paths,
                    )
                )
            else:
                issues.extend(_sync_file(root, mapping, check=args.check))
        print(f"Processed adapter: {platform}")
    if args.check and not selected_platforms:
        issues.extend(
            f"Orphan generated surface: {path.as_posix()}"
            for path in _find_orphan_generated_surfaces(root, all_mappings)
        )
    if issues:
        print("Agent adapter sync check failed:")
        for issue in issues:
            print(f"- {issue}")
        return 1
    if args.check:
        print("Agent adapter outputs are up to date.")
    else:
        print("Agent adapter outputs synchronized.")
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
