"""
@meta
name: validate_generated_header_format
type: script
domain: validation
distribution_tier: starter_kit
responsibility:
  - Validate generated artifact header format for text/markdown and JSON outputs.
lifecycle:
  status: active
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Finding:
    category: str
    path: str
    message: str


TEXT_HEADER_MARKER = "GENERATED FILE - DO NOT EDIT"
TEXT_SOURCE_MARKER = "Source: "
TEXT_GENERATED_BY_MARKER = "Generated by: scripts/sync_agent_adapters.py"
TEXT_UPDATE_MARKER = "To update: edit canonical source, then run sync."


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate generated header formats.")
    parser.add_argument("--repo-root", default=str(repo_root()))
    return parser.parse_args()


def _relative(path: Path, root: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def _is_json_file(path: Path) -> bool:
    return path.suffix.lower() == ".json"


def _validate_text_header(path: Path, rel: str) -> list[Finding]:
    findings: list[Finding] = []
    text = path.read_text(encoding="utf-8", errors="ignore")
    if not text.startswith("---\n") and not text.startswith("<!--\n"):
        findings.append(Finding("generated_header_error", rel, "generated text file must start with frontmatter or generated HTML comment header."))
        return findings
    if TEXT_HEADER_MARKER not in text:
        findings.append(Finding("generated_header_error", rel, "missing `GENERATED FILE - DO NOT EDIT` marker."))
    if TEXT_SOURCE_MARKER not in text:
        findings.append(Finding("generated_header_error", rel, "missing `Source:` marker."))
    if TEXT_GENERATED_BY_MARKER not in text:
        findings.append(Finding("generated_header_error", rel, "missing canonical `Generated by:` marker."))
    if TEXT_UPDATE_MARKER not in text:
        findings.append(Finding("generated_header_error", rel, "missing canonical update instruction marker."))
    if "GENERATED FILE - do not edit directly." in text:
        findings.append(Finding("generated_header_error", rel, "legacy generated header format is not allowed."))
    return findings


def _validate_json_header(path: Path, rel: str) -> list[Finding]:
    findings: list[Finding] = []
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return [Finding("generated_header_error", rel, f"invalid JSON: {exc}")]
    if not isinstance(payload, dict):
        return [Finding("generated_header_error", rel, "generated JSON payload must be an object.")]
    if payload.get("_generated") is not True:
        findings.append(Finding("generated_header_error", rel, "`_generated` must be true."))
    if not isinstance(payload.get("_source"), str) or not payload["_source"].strip():
        findings.append(Finding("generated_header_error", rel, "`_source` must be a non-empty string."))
    if payload.get("_generated_by") != "scripts/sync_agent_adapters.py":
        findings.append(Finding("generated_header_error", rel, "`_generated_by` must equal scripts/sync_agent_adapters.py."))
    if payload.get("_do_not_edit") != "Edit canonical source and run sync.":
        findings.append(Finding("generated_header_error", rel, "`_do_not_edit` must match canonical text."))
    return findings


def validate(root: Path) -> list[Finding]:
    findings: list[Finding] = []
    generated_root = root / "generated_agents"
    if not generated_root.exists():
        return findings
    allowed_provider_dirs = {"codex", "claude", "antigravity"}
    for path in sorted(p for p in generated_root.rglob("*") if p.is_file()):
        relative = path.relative_to(generated_root)
        if not relative.parts or relative.parts[0] not in allowed_provider_dirs:
            continue
        rel = _relative(path, root)
        if _is_json_file(path):
            findings.extend(_validate_json_header(path, rel))
        else:
            findings.extend(_validate_text_header(path, rel))
    return findings


def main() -> int:
    args = parse_args()
    root = Path(args.repo_root).resolve()
    findings = validate(root)
    if findings:
        print("Generated header format validation failed:")
        for finding in findings:
            print(f"- {finding.category}: {finding.path} - {finding.message}")
        return 1
    print("Generated header format validation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
